import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: "autogenerated", dirName: "."}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "Getting-Started",
    "Theming",
    "Restyle-functions",
    "Colors",
    {
      type: "category",
      label: "Compnents",
      items: [
        "components/Text",
        "components/Box",
        "components/Icon",
         "components/Badge",
         "components/Checkbox",
         "components/Switch",
         "components/Clickable",
        {
          type: "category",
          label: "Button",
          items: [
            "components/Button/button",
            "components/Button/Button.Icon",
            "components/Button/Button.Text",
          ],
        },
        {
          type: "category",
          label: "List",
          items: [
            "components/List/List.Accordion",
            "components/List/List.Icon",
            "components/List/List.Item",
          ],
        },
        {
          type: "category",
          label: "Radio",
          items: [
            "components/Radio/Radio",
            "components/Radio/Radio.RadioButton",
          ],
        },
      ],
    },
   
  ],
};

export default sidebars;
